language: scala
scala:
   - 2.12.6

sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

script:
  - sbt ++$TRAVIS_SCALA_VERSION reload compile test:compile

jdk:
  - oraclejdk8
  - oraclejdk9

notifications:
  email:
    - istvan.l.papp@gmail.com

after_success:
  - util/generate-latest-docs.sh
  - util/compareBuilds.sh
  - util/publish-snapshot-on-commit.sh

branches:
  only:
    - master